In [24]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import tensorflow as tf
from tensorflow.keras import layers, Model
import pandas as pd

In [25]:
x_coords_1 = [-17.68,-12.62,-7.57,-2.52,2.53,7.57,12.62,17.67]
y_coords_1 = [0,0,0,0,0,0,0,0]  
z_coords_1 = [-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61]
input_temperature_1 = 373
ambient_temperature_1 = 300
temp_diff_1 = input_temperature_1 - ambient_temperature_1
temp_diff_1=[temp_diff_1,temp_diff_1,temp_diff_1,temp_diff_1,temp_diff_1,temp_diff_1,temp_diff_1,temp_diff_1]
input_temperature_1 =[input_temperature_1,input_temperature_1,input_temperature_1,input_temperature_1,input_temperature_1,input_temperature_1,input_temperature_1,input_temperature_1]

In [26]:
x_coords_2 = [-17.68,-12.62,-7.57,-2.52,2.53,7.57,12.62,17.67]
y_coords_2 = [0,0,0,0,0,0,0,0]  
z_coords_2 = [-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61]
input_temperature_2 = 383
ambient_temperature_2 = 290
temp_diff_2 = input_temperature_2 - ambient_temperature_2
temp_diff_2=[temp_diff_2,temp_diff_2,temp_diff_2,temp_diff_2,temp_diff_2,temp_diff_2,temp_diff_2,temp_diff_2]
input_temperature_2 =[input_temperature_2,input_temperature_2,input_temperature_2,input_temperature_2,input_temperature_2,input_temperature_2,input_temperature_2,input_temperature_2]

In [27]:
x_coords_3 = [-17.68,-12.62,-7.57,-2.52,2.53,7.57,12.62,17.67]
y_coords_3 = [0,0,0,0,0,0,0,0]  
z_coords_3 = [-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61]
input_temperature_3 = 400.0
ambient_temperature_3 = 310.0
temp_diff_3 = input_temperature_3 - ambient_temperature_3
temp_diff_3=[temp_diff_3,temp_diff_3,temp_diff_3,temp_diff_3,temp_diff_3,temp_diff_3,temp_diff_3,temp_diff_3]
input_temperature_3 =[input_temperature_3,input_temperature_3,input_temperature_3,input_temperature_3,input_temperature_3,input_temperature_3,input_temperature_3,input_temperature_3]

In [28]:
x_coords_4 = [-17.68,-12.62,-7.57,-2.52,2.53,7.57,12.62,17.67]
y_coords_4 = [0,0,0,0,0,0,0,0]  
z_coords_4 = [-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61]
input_temperature_4 = 395
ambient_temperature_4 = 295
temp_diff_4 = input_temperature_4 - ambient_temperature_4
temp_diff_4=[temp_diff_4,temp_diff_4,temp_diff_4,temp_diff_4,temp_diff_4,temp_diff_4,temp_diff_4,temp_diff_4]
input_temperature_4 =[input_temperature_4,input_temperature_4,input_temperature_4,input_temperature_4,input_temperature_4,input_temperature_4,input_temperature_4,input_temperature_4]

In [29]:
x_coords_5 = [-17.68,-12.62,-7.57,-2.52,2.53,7.57,12.62,17.67]
y_coords_5 = [0,0,0,0,0,0,0,0]  
z_coords_5 = [-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61,-12.61]
input_temperature_5 = 380
ambient_temperature_5 = 305
temp_diff_5 = input_temperature_5 - ambient_temperature_5
temp_diff_5=[temp_diff_5,temp_diff_5,temp_diff_5,temp_diff_5,temp_diff_5,temp_diff_5,temp_diff_5,temp_diff_5]
input_temperature_5 =[input_temperature_5,input_temperature_5,input_temperature_5,input_temperature_5,input_temperature_5,input_temperature_5,input_temperature_5,input_temperature_5]

In [30]:
X_train_1 = np.column_stack((x_coords_1, y_coords_1, z_coords_1, input_temperature_1, temp_diff_1))
X_train_1

array([[-17.68,   0.  , -12.61, 373.  ,  73.  ],
       [-12.62,   0.  , -12.61, 373.  ,  73.  ],
       [ -7.57,   0.  , -12.61, 373.  ,  73.  ],
       [ -2.52,   0.  , -12.61, 373.  ,  73.  ],
       [  2.53,   0.  , -12.61, 373.  ,  73.  ],
       [  7.57,   0.  , -12.61, 373.  ,  73.  ],
       [ 12.62,   0.  , -12.61, 373.  ,  73.  ],
       [ 17.67,   0.  , -12.61, 373.  ,  73.  ]])

In [31]:
X_train_2 = np.column_stack((x_coords_2, y_coords_2, z_coords_2, input_temperature_2, temp_diff_2))
X_train_2

array([[-17.68,   0.  , -12.61, 383.  ,  93.  ],
       [-12.62,   0.  , -12.61, 383.  ,  93.  ],
       [ -7.57,   0.  , -12.61, 383.  ,  93.  ],
       [ -2.52,   0.  , -12.61, 383.  ,  93.  ],
       [  2.53,   0.  , -12.61, 383.  ,  93.  ],
       [  7.57,   0.  , -12.61, 383.  ,  93.  ],
       [ 12.62,   0.  , -12.61, 383.  ,  93.  ],
       [ 17.67,   0.  , -12.61, 383.  ,  93.  ]])

In [32]:
X_train_3 = np.column_stack((x_coords_3, y_coords_3, z_coords_3, input_temperature_3, temp_diff_3))
X_train_3

array([[-17.68,   0.  , -12.61, 400.  ,  90.  ],
       [-12.62,   0.  , -12.61, 400.  ,  90.  ],
       [ -7.57,   0.  , -12.61, 400.  ,  90.  ],
       [ -2.52,   0.  , -12.61, 400.  ,  90.  ],
       [  2.53,   0.  , -12.61, 400.  ,  90.  ],
       [  7.57,   0.  , -12.61, 400.  ,  90.  ],
       [ 12.62,   0.  , -12.61, 400.  ,  90.  ],
       [ 17.67,   0.  , -12.61, 400.  ,  90.  ]])

In [33]:
X_train_4 = np.column_stack((x_coords_4, y_coords_4, z_coords_4, input_temperature_4, temp_diff_4))
X_train_4

array([[-17.68,   0.  , -12.61, 395.  , 100.  ],
       [-12.62,   0.  , -12.61, 395.  , 100.  ],
       [ -7.57,   0.  , -12.61, 395.  , 100.  ],
       [ -2.52,   0.  , -12.61, 395.  , 100.  ],
       [  2.53,   0.  , -12.61, 395.  , 100.  ],
       [  7.57,   0.  , -12.61, 395.  , 100.  ],
       [ 12.62,   0.  , -12.61, 395.  , 100.  ],
       [ 17.67,   0.  , -12.61, 395.  , 100.  ]])

In [34]:
res_1=[373,364.8,356.7,340.5,332.4,316.2,308.1,300]
y_train_1=np.array(res_1)
y_train_1

array([373. , 364.8, 356.7, 340.5, 332.4, 316.2, 308.1, 300. ])

In [35]:
res_2=[383,372.6,362.3,341.6,331.3,310.6,300.3,290]
y_train_2=np.array(res_2)
y_train_2

array([383. , 372.6, 362.3, 341.6, 331.3, 310.6, 300.3, 290. ])

In [12]:
res_3=[400,389.9,379.9,359.9,349.9,329.9,319.9,310]
y_train_3=np.array(res_3)
y_train_3

array([400. , 389.9, 379.9, 359.9, 349.9, 329.9, 319.9, 310. ])

In [13]:
res_4=[395,383.8,372.7,350.5,339.4,317.2,306.09,295]
y_train_4=np.array(res_4)
y_train_4

In [ ]:
res_5=[380,371.6,363.3,346.6,338.3,321.65,313.3,305]
y_train_5=np.array(res_5)
y_train_5

In [14]:
class PINN(Model):
    def __init__(self):
        super(PINN, self).__init__()
        self.dense1 = layers.Dense(64, activation='relu')
        self.dense2 = layers.Dense(32, activation='relu')
        self.dense3 = layers.Dense(1)

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)


In [15]:
def custom_loss(y_true, y_pred, X_train):
    data_loss = tf.reduce_mean(tf.square(y_true - y_pred))
    
    # Physics-informed regularization term based on the heat equation
    alpha = 1.0  # Thermal diffusivity
    with tf.GradientTape() as tape:
        tape.watch(X_train)
        y_pred_with_grad = model(X_train)
        gradients = tape.gradient(y_pred_with_grad, X_train)
        laplacian = tf.reduce_sum(tf.square(gradients), axis=1)
    physics_loss = tf.reduce_mean(alpha * laplacian)
    
    total_loss = data_loss + physics_loss
    return total_loss

In [16]:
model = PINN()

# Compile the model
model.compile(optimizer='adam', loss=lambda y_true, y_pred: custom_loss(y_true, y_pred, tf.convert_to_tensor(X_train_1, dtype=tf.float32)))
model.compile(optimizer='adam', loss=lambda y_true, y_pred: custom_loss(y_true, y_pred, tf.convert_to_tensor(X_train_2, dtype=tf.float32)))
model.compile(optimizer='adam', loss=lambda y_true, y_pred: custom_loss(y_true, y_pred, tf.convert_to_tensor(X_train_3, dtype=tf.float32)))
# model.compile(optimizer='adam', loss=lambda y_true, y_pred: custom_loss(y_true, y_pred, tf.convert_to_tensor(X_train_4, dtype=tf.float32)))



In [17]:
model.fit(tf.convert_to_tensor(X_train_1, dtype=tf.float32), tf.convert_to_tensor(y_train_1, dtype=tf.float32), epochs=1000, verbose=0)


In [18]:
model.fit(tf.convert_to_tensor(X_train_2, dtype=tf.float32), tf.convert_to_tensor(y_train_2, dtype=tf.float32), epochs=1000, verbose=0)
model.fit(tf.convert_to_tensor(X_train_3, dtype=tf.float32), tf.convert_to_tensor(y_train_3, dtype=tf.float32), epochs=1000, verbose=0)
# model.fit(tf.convert_to_tensor(X_train_4, dtype=tf.float32), tf.convert_to_tensor(y_train_4, dtype=tf.float32), epochs=1000, verbose=0)


In [19]:
input_temperature_test = 395
ambient_temperature_test = 295
temp_diff_test = input_temperature_test - ambient_temperature_test
temp_diff_test=[temp_diff_test,temp_diff_test,temp_diff_test,temp_diff_test,temp_diff_test,temp_diff_test,temp_diff_test,temp_diff_test]
input_temperature_test =[input_temperature_test,input_temperature_test,input_temperature_test,input_temperature_test,input_temperature_test,input_temperature_test,input_temperature_test,input_temperature_test]

In [20]:
X_test = np.column_stack((x_coords_1, y_coords_1, z_coords_1, input_temperature_test, temp_diff_test))
X_test

array([[-17.68,   0.  , -12.61, 395.  , 100.  ],
       [-12.62,   0.  , -12.61, 395.  , 100.  ],
       [ -7.57,   0.  , -12.61, 395.  , 100.  ],
       [ -2.52,   0.  , -12.61, 395.  , 100.  ],
       [  2.53,   0.  , -12.61, 395.  , 100.  ],
       [  7.57,   0.  , -12.61, 395.  , 100.  ],
       [ 12.62,   0.  , -12.61, 395.  , 100.  ],
       [ 17.67,   0.  , -12.61, 395.  , 100.  ]])

In [21]:
y_pred = model.predict(tf.convert_to_tensor(X_test, dtype=tf.float32))

In [22]:
y_pred

array([[404.49445],
       [390.9951 ],
       [377.52243],
       [364.0497 ],
       [350.57703],
       [337.131  ],
       [323.65833],
       [310.18564]], dtype=float32)